apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "capa-eks-control-plane.fullname" . }}-mutating-webhook-configuration
  labels:
    cluster.x-k8s.io/provider: control-plane-eks
  {{- include "capa-eks-control-plane.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: capi-webhook-system/capa-eks-control-plane-serving-cert
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: capa-eks-control-plane-webhook-service
      namespace: capi-webhook-system
      path: /mutate-controlplane-cluster-x-k8s-io-v1alpha3-awsmanagedcontrolplane
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedcontrolplanes
  sideEffects: None