apiVersion: v1
kind: Service
metadata:
  name: {{ include "capa-eks-control-plane.fullname" . }}-webhook-service
  labels:
    cluster.x-k8s.io/provider: control-plane-eks
  {{- include "capa-eks-control-plane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    cluster.x-k8s.io/provider: control-plane-eks
  {{- include "capa-eks-control-plane.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}